Models/Room.cs
using System.ComponentModel.DataAnnotations;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json.Serialization;

namespace RoombookingApp.Models
{
    public class Room
    {
        public int Id { get; set; }
        [Required]
        public string? Name { get; set; }
        [JsonIgnore]
        public List<Reservation> Reservations { get; set; } = new();
    }
    public class RoomAvailabilityRequest
    {
        public DateTime From { get; set; }
        public DateTime To { get; set; }
    }
    public class RoomRequest
    {
        public string? Name { get; set; }
    }
    public class ReservationRequest
    {
        public RoomAvailabilityRequest TimeRequest { get; set; }
        public Room Room { get; set; }
    }

}

Controllers/ReservationsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RoombookingApp.Middleware;
using RoombookingApp.Models;

namespace RoombookingApp.Controllers
{
    public class ReservationsController : Controller
    {
        private readonly ReservationService _reservationService;

        public ReservationsController(ReservationService reservationService)
        { _reservationService = reservationService; }
        public IActionResult Index()
        {
            return View();
        }

        // przejscie do formularza zeby ustalic dane widelki czasowe 
        // gdzie chcemy sprawdzic jakie pokoje sa wolne
        [HttpGet]
        [RequireLoggedIn]
        public IActionResult GetAvailableRooms()
        {
            return View();
        }

        //wyswietlenie przefiltrowanych pokoi z walidacja danych
        [HttpPost]
        [RequireLoggedIn]
        public IActionResult GetAvailableRooms(RoomAvailabilityRequest request)
        {
            if (request.From >= request.To)
            { return BadRequest("Data rozpoczęcia rezerwacji musi być wcześniejsza niż data zakończenia."); }
            
            var rooms = _reservationService.GetAvailableRooms(request.From, request.To);
            ViewData["From"] = request.From;
            ViewData["To"] = request.To;
            return View("~/Views/Rooms/Index.cshtml", rooms);
        }
        [HttpGet]
        [RequireLoggedIn]
        public IActionResult ReserveRoom(int id)
        {
            ViewData["RoomId"] = id;
            ViewData["userId"] = HttpContext.Session.GetInt32("user_id");
            return View();
        }
        [HttpPost]
        [RequireLoggedIn]
        public async Task<IActionResult> ReserveRoom(int id, RoomAvailabilityRequest request)
        {
            int userId = HttpContext.Session.GetInt32("user_id") ?? 0;

            if (request.From >= request.To)
            { return BadRequest("Data rozpoczęcia rezerwacji musi być wcześniejsza niż data zakończenia."); }
            
            if (request.From < DateTime.Now)
            { return BadRequest("Data rozpoczecia musi byc późniejsza niz aktualny czas"); }

            var existingRoom = await _reservationService.Rooms
                .FirstOrDefaultAsync(r => r.Id == id);
            var rooms = _reservationService.GetAvailableRooms(request.From, request.To);
            
            if (existingRoom == null)
            { return BadRequest("nie ma takiego pokoju"); }

            if (!rooms.Contains(existingRoom))
            { return BadRequest("ten pokoj jest zajety"); }

            await _reservationService.ReserveRoom(request.From, request.To, existingRoom.Name, userId);
            return Ok(new { message = "rezerwacja udana" });
        }
        [RequireLoggedIn]
        public IActionResult GetMyReservation()
        {
            int userId = HttpContext.Session.GetInt32("user_id") ?? 0;
            var reservations = _reservationService.GetMyReservation(userId);
            if (reservations.Count == 0)
            {
                return Ok(new { message = "nie masz rezerwacji." });
            }
            return View(reservations);
        }

        [RequireLoggedIn]
        public IActionResult GetMyArchivedReservation()
        {
            int userId = HttpContext.Session.GetInt32("user_id") ?? 0;
            var reservations = _reservationService.GetMyArchivedReservation(userId);
            if (reservations.Count == 0)
            {
                return Ok(new { message = "nie masz rezerwacji." });
            }
            return View(reservations);
        }

        [RequireLoggedIn]
        public async Task<IActionResult> DeleteReservation(int id)
        {
            int userId = HttpContext.Session.GetInt32("user_id") ?? 0;
            bool deleted = await _reservationService.DeleteReservation(id, userId);
            if (!deleted)
            { return NotFound(new { message = "Nie znaleziono rezerwacji lub brak uprawnień." }); }

            return RedirectToAction("GetMyReservation");

        }
    }
}

Controllers/RoomsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RoombookingApp.Data;
using RoombookingApp.Middleware;
using RoombookingApp.Models;

namespace RoombookingApp.Controllers
{
    public class RoomsController : Controller
    {
        private readonly AppDbContext _context;

        public RoomsController(AppDbContext context)
        {
            _context = context;
        }
        [RequireLoggedIn]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Rooms.ToListAsync());
        }
        [RequireLoggedIn]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var room = await _context.Rooms
                .Include(r => r.Reservations)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (room == null)
            {
                return NotFound();
            }

            return View(room);
        }
        [RequireLoggedIn]
        public IActionResult Create()
        {
            return View();
        }

        [RequireLoggedIn]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Room room)
        {
            if (ModelState.IsValid)
            {
                _context.Add(room);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(room);
        }
        [RequireLoggedIn]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var room = await _context.Rooms.FindAsync(id);
            if (room == null)
            {
                return NotFound();
            }
            return View(room);
        }

        [RequireLoggedIn]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Room room)
        {
            if (id != room.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(room);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RoomExists(room.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(room);
        }

        [RequireLoggedIn]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var room = await _context.Rooms
                .FirstOrDefaultAsync(m => m.Id == id);
            if (room == null)
            {
                return NotFound();
            }

            return View(room);
        }

        [RequireLoggedIn]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var room = await _context.Rooms.FindAsync(id);
            if (room != null)
            {
                _context.Rooms.Remove(room);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RoomExists(int id)
        {
            return _context.Rooms.Any(e => e.Id == id);
        }
    }
}

Views/Rooms/Create.cshtml
@model RoombookingApp.Models.Room

@{
    ViewData["Title"] = "Create";
}
<div style="margin-top: 24px">
    <a asp-action="Index">Back to List</a>
</div>

<h1>Create Room</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" style="margin-top: 8px"  value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Rooms/Delete.cshtml
@model RoombookingApp.Models.Room

@{
    ViewData["Title"] = "Delete";
   
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Room</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Rooms/Details.cshtml
@model RoombookingApp.Models.Room

@{
    ViewData["Title"] = "Details";

}

<h1>Details</h1>

<div>
    <h4>Room</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    <dt>Reservations</dt>
        @foreach( var item in Model.Reservations )
        {
         @if (item.ReservationTo>DateTime.Now)
         {
            <p>
                From: @Html.DisplayFor(modelItem => item.ReservationFrom)
                To: @Html.DisplayFor(modelItem => item.ReservationTo)
            </p>
          }
        }
    
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Rooms/Edit.cshtml
@model RoombookingApp.Models.Room

@{
    ViewData["Title"] = "Edit";
  
}

<h1>Edit</h1>

<h4>Room</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Rooms/Index.cshtml
@model IEnumerable<RoombookingApp.Models.Room>

@{
    ViewData["Title"] = "Index";
  
}

@if (ViewData["From"] != null && ViewData["To"] != null)
{
    <p>Pokazuje dostępne pokoje od @ViewData["From"] do @ViewData["To"]</p>
}
else
{
    <p>Lista wszystkich pokoi:</p>
    
}

<p>
    <a asp-action="Create">Create New</a> <a asp-controller="Reservations" asp-action="GetAvailableRooms">Filter Room</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a> |
                <a asp-controller="Reservations" asp-action="ReserveRoom" asp-route-id="@item.Id">Reserve room</a>
            </td>
        </tr>
}
    </tbody>
</table>